import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const links = [
    { label: "Nous Connaitre" },
    { label: "Applications" },
    { label: "Réseaux" },
    { label: "QHSE" },
    { label: "Actualités" },
  ];
  return (
    <html lang="en">
      <body className="antialiased font-poppins">
        <NavBar Links={links} logo="/maghriboxygen/logo.png" />

        {children}
        <Footer links={links} />
      </body>
    </html>
  );
}
