import type { Metadata } from "next";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Afriquia Gaz",
  description: "Generated by Afriquia Gaz",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={`font-poppins antialiased`}>
      <Providers>{children}</Providers>
    </main>
  );
}
